server {
    listen 80;
    server_name sefyadentalstudio.web.id;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name sefyadentalstudio.web.id;

    ssl_certificate /etc/letsencrypt/live/sefyadentalstudio.web.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sefyadentalstudio.web.id/privkey.pem;

    root /opt/mahzuz/frontend/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8080;
    }

    location /uploads/ {
        proxy_pass http://127.0.0.1:8080;
    }
}
